name: Classic City Cotton
favicon: null
layout_spectrum: 0.78998545370996
typography_spectrum: 0.47039549774490297
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.21725223935209215
  lightness: 0.9554351894184947
  saturation: 0.4460187628865242
  rhythmicContrast: 0.9025607092771679
purpose: []
